### PR TITLE
Create page improvements

### PR DESCRIPTION
**Pull request by evguu**
Draft PRs are good for commenting changes on the go, so I'll open it preemptively again

### CODE REVIEW

**Comment by evguu** [comment]
Solves #72

**Comment by evguu** [comment]
Changelist:

1. Improved UX for image orientation presets
2. Added button to swap width and height (visible when Custom orientation is selected)
3. UI provides more information about dimensions now
4. Added "Lock aspect ratio" button. It tries its best, don't judge the poor fellow :hand_over_mouth: 
5. ControlNet options don't clutter the page when unavailable. The option itself is still shown so that users know it exists.

**Comment by evguu** [comment]
(also ignore the branch name, it's not related to the PR)

**Review by daveschumaker — APPROVED** [review]
**FANTASTIC** 👏🏻👏🏻👏🏻 🎉

**Pull request merged**
